import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { getPlanRequest, getCourseByIdRequest } from '../api/course.api';
import { getCourseProgressRequest } from '../api/stats.api';

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

function buildPlanHtml(
  course: { title: string; aiProvider: string; startDate: string; endDate: string; durationValue: number; durationUnit: string },
  plan: { days: { dayNumber: number; date: string; topic: string; subtopics: string[]; estimatedMinutes: number; status: string }[] },
  progress: { completedDays: number; totalDays: number; percentage: number }
) {
  const rows = plan.days
    .map(
      (day) => `
        <tr>
          <td class="day-num">${day.dayNumber}</td>
          <td>
            <div class="topic">${escapeHtml(day.topic)}</div>
            <div class="subtopics">${escapeHtml(day.subtopics.join(' · '))}</div>
          </td>
          <td class="center">${formatDate(day.date)}</td>
          <td class="center">${day.estimatedMinutes} min</td>
          <td class="center">
            <span class="badge ${day.status === 'completed' ? 'badge-done' : 'badge-pending'}">
              ${day.status === 'completed' ? '✓ Done' : 'Pending'}
            </span>
          </td>
        </tr>`
    )
    .join('');

  return `
    <html>
      <head>
        <meta charset="utf-8" />
        <style>
          * { box-sizing: border-box; }
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #12131A; padding: 32px; }
          .header { background: #4A47A3; border-radius: 16px; padding: 24px; color: #fff; margin-bottom: 24px; }
          .brand { font-size: 13px; opacity: 0.85; letter-spacing: 1px; margin-bottom: 8px; }
          .title { font-size: 24px; font-weight: 700; margin-bottom: 4px; }
          .meta { font-size: 13px; opacity: 0.9; }
          .progress-wrap { margin-top: 16px; background: rgba(255,255,255,0.2); border-radius: 999px; height: 10px; overflow: hidden; }
          .progress-fill { background: #F2A93B; height: 100%; width: ${progress.percentage}%; }
          .progress-label { font-size: 12px; margin-top: 6px; opacity: 0.9; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; }
          th { text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #7A7A87; padding: 8px 10px; border-bottom: 2px solid #EEEEF2; }
          td { padding: 10px; border-bottom: 1px solid #EEEEF2; font-size: 13px; vertical-align: top; }
          .day-num { font-weight: 700; color: #4A47A3; width: 32px; }
          .topic { font-weight: 600; margin-bottom: 2px; }
          .subtopics { font-size: 11px; color: #7A7A87; }
          .center { text-align: center; white-space: nowrap; }
          .badge { display: inline-block; padding: 3px 10px; border-radius: 999px; font-size: 11px; font-weight: 600; }
          .badge-done { background: #2FB57422; color: #2FB574; }
          .badge-pending { background: #EEEEF2; color: #7A7A87; }
          .footer { margin-top: 24px; text-align: center; font-size: 11px; color: #9C9CA8; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="brand">📚 STUDYPILOT — STUDY PLAN</div>
          <div class="title">${escapeHtml(course.title)}</div>
          <div class="meta">
            ${formatDate(course.startDate)} – ${formatDate(course.endDate)}
            · ${course.durationValue} ${course.durationUnit}
            · AI Provider: ${course.aiProvider.charAt(0).toUpperCase() + course.aiProvider.slice(1)}
          </div>
          <div class="progress-wrap"><div class="progress-fill"></div></div>
          <div class="progress-label">${progress.completedDays} of ${progress.totalDays} days complete (${progress.percentage}%)</div>
        </div>

        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Topic</th>
              <th class="center">Date</th>
              <th class="center">Est. Time</th>
              <th class="center">Status</th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>

        <div class="footer">Generated by StudyPilot on ${formatDate(new Date().toISOString())}</div>
      </body>
    </html>
  `;
}

export async function exportStudyPlanPdf(courseId: string): Promise<string> {
  const [course, plan, progress] = await Promise.all([
    getCourseByIdRequest(courseId),
    getPlanRequest(courseId),
    getCourseProgressRequest(courseId),
  ]);

  const html = buildPlanHtml(course, plan, progress);
  const { uri } = await Print.printToFileAsync({ html, base64: false });

  const canShare = await Sharing.isAvailableAsync();
  if (canShare) {
    await Sharing.shareAsync(uri, {
      mimeType: 'application/pdf',
      dialogTitle: `${course.title} — Study Plan`,
      UTI: 'com.adobe.pdf',
    });
  }

  return uri;
}