import jsPDF from 'jspdf';

const MARGIN = 48;
const PAGE_WIDTH = 595.28; // A4 pt
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const LINE_HEIGHT = 16;

/** Strips common markdown syntax down to readable plain text for PDF rendering. */
function stripMarkdown(md = '') {
  return md
    .replace(/```[\s\S]*?```/g, (block) => block.replace(/```(\w+)?/g, '').trim())
    .replace(/^#{1,6}\s+/gm, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
    .replace(/^\s*[-*]\s+/gm, '• ')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim();
}

function addHeader(doc, title, subtitle) {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor('#111915');
  doc.text(title, MARGIN, 60);

  if (subtitle) {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor('#87988F');
    doc.text(subtitle, MARGIN, 78);
  }

  doc.setDrawColor('#E6EBE8');
  doc.line(MARGIN, 90, PAGE_WIDTH - MARGIN, 90);
  return 118;
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i += 1) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor('#87988F');
    doc.text('Generated by StudyPilot', MARGIN, 820);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN - 60, 820);
  }
}

function ensureSpace(doc, y, needed = LINE_HEIGHT) {
  if (y + needed > 780) {
    doc.addPage();
    return 60;
  }
  return y;
}

function writeParagraph(doc, text, y, { size = 10, color = '#111915', bold = false } = {}) {
  doc.setFont('helvetica', bold ? 'bold' : 'normal');
  doc.setFontSize(size);
  doc.setTextColor(color);

  const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
  for (const line of lines) {
    y = ensureSpace(doc, y);
    doc.text(line, MARGIN, y);
    y += LINE_HEIGHT;
  }
  return y;
}

export function exportDayToPdf(course, day) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = addHeader(doc, `Day ${day.dayNumber}: ${day.topic}`, course.title);

  if (day.subtopics?.length > 0) {
    y = writeParagraph(doc, day.subtopics.join(' · '), y, { size: 9, color: '#526359' });
    y += 8;
  }

  if (day.content) {
    y = writeParagraph(doc, stripMarkdown(day.content), y);
    y += 12;
  }

  if (day.keyConcepts?.length > 0) {
    y = ensureSpace(doc, y, 24);
    y = writeParagraph(doc, 'Key Concepts', y, { size: 12, bold: true, color: '#059669' });
    y += 4;
    for (const concept of day.keyConcepts) {
      y = writeParagraph(doc, `•  ${concept}`, y);
    }
    y += 12;
  }

  if (day.tips?.length > 0) {
    y = ensureSpace(doc, y, 24);
    y = writeParagraph(doc, 'Tips', y, { size: 12, bold: true, color: '#059669' });
    y += 4;
    for (const tip of day.tips) {
      y = writeParagraph(doc, `•  ${tip}`, y, { color: '#526359' });
    }
  }

  addFooter(doc);
  doc.save(`${course.title.replace(/[^a-z0-9]+/gi, '-')}-day-${day.dayNumber}.pdf`);
}

export function exportCourseToPdf(course, plan) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = addHeader(
    doc,
    course.title,
    `${course.durationValue} ${course.durationUnit} · ${plan.days.length} days · AI: ${course.aiProvider}`
  );

  for (const day of plan.days) {
    y = ensureSpace(doc, y, 40);
    y = writeParagraph(doc, `Day ${day.dayNumber}: ${day.topic}`, y, { size: 12, bold: true });

    if (day.subtopics?.length > 0) {
      y = writeParagraph(doc, day.subtopics.join(' · '), y, { size: 9, color: '#87988F' });
    }

    y = writeParagraph(
      doc,
      `${day.estimatedMinutes} min · ${day.status === 'completed' ? 'Completed' : 'Pending'}`,
      y,
      { size: 9, color: day.status === 'completed' ? '#059669' : '#87988F' }
    );
    y += 10;
  }

  addFooter(doc);
  doc.save(`${course.title.replace(/[^a-z0-9]+/gi, '-')}-plan.pdf`);
}